name: Deploy API script

on:
  push:
    branches: ["main"]
    paths:
      - "shared/**"
      - "api/**"
      - ".github/workflows/deploy_api.yml"
      - "config-clasp.ts"
      - "package-lock.json"

  workflow_dispatch:

permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "api"
  cancel-in-progress: false

jobs:
  deploy:
    environment: api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: "package-lock.json"
      - name: Install packages
        run: npm ci
      - name: Build script
        run: npm run build-api
        env:
          PATREON_KEY: ${{ secrets.PATREON_KEY }}
          SS_LINK: ${{ secrets.SS_LINK }}
      # - name: Test script
      #   run: npm run test-api
      - name: Configure Clasp
        run: npm run config-api
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
          SCRIPT_ID: ${{ secrets.SCRIPT_ID_API }}
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID_API }}
      - run: cd api/dist/ && ls -a
      - name: Deploy script
        run: npm run deploy-api
        env:
          DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID_API }}
